# Production values for HTTP mode
slack:
  # Disable socket mode to use HTTP mode
  socketMode: false
  port: 3000

# Enable ingress for HTTP mode
ingress:
  enabled: true
  className: ""
  annotations:
    # Enable HTTPS redirect
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Increase body size for file uploads
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  hosts:
    - host: slack.peerbot.ai
      paths:
        - path: /slack
          pathType: Prefix
  tls:
    - secretName: peerbot-tls
      hosts:
        - slack.peerbot.ai

# Increase replicas for HTTP mode
dispatcher:
  replicaCount: 2