apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: peerbot-backend-config
  namespace: peerbot
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
    port: 8080